name: Searching checks

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    perfts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: cd test && cp ../nnue.bin . && g++ -o perfts.out perfts.cpp ../engine/bitboard.cpp ../engine/movegen.cpp ../engine/search.cpp ../engine/eval.cpp ../engine/ttable.cpp ../engine/nnue/network.cpp -O3 -mbmi -mbmi2 -m64 -mlzcnt -mavx2 -mpopcnt -fPIC -DPERFT -std=c++17
            - name: test
              run: ./test/perfts.out
    positions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: cd test && cp ../nnue.bin . && g++ -o search.out search.cpp ../engine/bitboard.cpp ../engine/movegen.cpp ../engine/search.cpp ../engine/eval.cpp ../engine/ttable.cpp ../engine/nnue/network.cpp -O3 -mbmi -mbmi2 -m64 -mlzcnt -mavx2 -mpopcnt -fPIC -std=c++17
            - name: test
              run: ./test/search.out
