name: Perft checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.81.0
        libraries: process
        platform: x64
        configuration: Release

    - name: Show paths
      run: |
        printf 'Boost has been unpacked to: %s\n' '${{ steps.boost.outputs.root }}'
        printf 'Libraries can be found here: %s\n' '${{ steps.boost.outputs.librarydir }}'
      shell: bash
    - name: compile engine
      run: cd engine && g++ *.cpp -O3 -mbmi -m64 -mlzcnt
    - name: compile test binary
      run: cd test && g++ main.cpp -O3
    - name: test
      run: ./test/a.out
