name: Perft checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.1
      id: install-boost
      with:
          boost_version: 1.81.0
          boost_install_dir: /home/runner/boost
          toolset: gcc
          arch: aarch64
    - name: list boost dir
      run: ls /home/runner/boost/boost/boost-1.81.0-ubuntu-20.04-gcc-static+shared-aarch64
    - name: compile engine
      run: cd engine && g++ *.cpp -O3 -mbmi -m64 -mlzcnt
    - name: compile test binary
      run: cd test && g++ main.cpp -O3
    - name: test
      run: ./test/a.out
